export default {
  logo: require('./logo.png'),
  user: require('./user.png'),
  userFocused: require('./userFocused.png'),
  logout: require('./logout.png'),
  menu: require('./menu.png'),
  home: require('./home.png'),
  homeFocused: require('./homeFocused.png'),
  settings: require('./settings.png'),
  settingsFocused: require('./settingsFocused.png'),
  create: require('./create.png'),
  createFocused: require('./createFocused.png'),
  video: require('./video.png'),
  videoFocused: require('./videoFocused.png'),
  backgroundImage: require('./backgroundImage.jpg'),
  darkBackgroundImage: require('./darkBackgroundImage.jpg'),
  placeholderImage: require('./placeholderImage.png'),
  downArrow: require('./downArrow.png'),
  rightArrow: require('./rightArrow.png'),
  search: require('./search.png'),
  notifications: require('./notifications.png'),
  notificationsFocused: require('./notificationsFocused.png'),
  lightTheme: require('./lightBackground.png'),
  darkTheme: require('./darkBackground.png'),
};
