export default {
  welcomeLogin: 'Welcome to Login Screen.',
  welcomeSignUp: 'Welcome to Login Screen.',
  welcomeSplash: 'Welcome to Grooooot!',
  enterEmail: 'Enter Email',
  enterName: 'Enter Full Name',
  enterPhone: 'Enter Mobile Number',
  enterCurrentPassword: 'Current Password',
  enterPassword: 'Enter Password',
  enterConfirmPassword: 'Enter Confirm Password',
  email: 'Email',
  firstName: 'First Name',
  lastName: 'Last Name',
  name: 'Full Name',
  mobileNo: 'Mobile Number',
  ok: 'Ok',
  welcome: 'Welcome!',
  cancelString: 'Cancel',
  login: 'Login',
  logout: 'Logout',
  signUp: 'Signup',
  homeDetail: 'Home Detail',
  createAccount: 'Create Account',
  noAccount: "Don't have an Account?",
  alreadyAccount: 'Already have an Account?',
  requiredField: 'This is required field.',
  invalidMobile: 'Please enter valid Mobile number.',
  passwordMinimumLength: 'Password should have minimum 8 characters.',
  notEmail: 'Not an email.',
  notName: 'It must be a name.',
  validCred: 'Enter Valid Credentials',
  accExist: 'Account Exist',
  userNotExist: "User doesn't Exist.",
  pleaseSignup: 'Looks like user does not Exist, please Signup.',
  pleaseLogin: 'Looks like user already exist, please Login.',
  invalidCred: 'Invalid Credentials',
  passwordNotMatching: 'Password does not match',
  invalidPass: 'Invalid Password',
  checkCredentials: 'Check User Credentials',
  create: 'Create',
  video: 'Video',
  videoDetail: 'Video Detail',
  subscribe: 'Subscribe',
  subscribed: 'Subscribed',
  errorOccurred: 'Some Error was Occurred',
  error: 'Error',
  permissionDenied: 'Permission Denied',
  accessGallery: 'Would you still like to give access to photo library?',
  sureLogout: 'Are you sure you want to Logout?',
  addUser: 'Add User',
  accessMultiple: 'Camera or Gallery',
  openCameraOrGallery: 'Access Camera or open Library',
  camera: 'Camera',
  gallery: 'Gallery',
  changePassword: 'Change Password',
  changeTheme: 'Change Theme',
  termsAndConditions: 'Terms And Conditions',
  privacyPolicy: 'Privacy Policy',
  version: 'Version 1.0.0',
  copyRight: '© Groot. All Right Reserved.',
  wrongPassword: 'Please enter correct Password',
  search: 'Search',
  editUser: 'Edit User',
  updateUser: 'Update User',
  noUser: 'No User Found',
  noNotifications: 'No Notifications to display.',
  clearNotifications: 'Clear Notifications',
  address: 'Address',
  gender: 'Gender',
  male: 'Male',
  fakeAddress: '6, Behramji Mansion, Sir P M Road, Fort, Maharashtra, Mumbai.',
  light: 'Light Theme',
  dark: 'Dark Theme',
  systemDefault: 'System Default',
  exitApp: 'Exit App',
  sureExitApp: 'Are you sure you want to Exit App?',
};
